### PR TITLE
Openlinks IPFS Blog

### PR DESCRIPTION
**Pull request by galaxyxtwo**
Added the Openlinks IPNS blog post to the "Read More" slider above the website footer. Removed the "Follow us on Twitter" placeholder in the slider. @noryev

### CODE REVIEW

**Comment by logan-wrld** [comment]
Add images and depictions of what changed pls @galaxyxtwo

**Comment by galaxyxtwo** [comment]
**Updated the assets and images** for 2 blog posts:"Why a decentralized Link-in-Bio?" and "Openlinks.io and IPNS" blog posts in the blog post slider. Also updated the corresponding images in the actual blog posts on medium.


Screenshot 2023-06-22 at 8 56 01 PM

**New image^ for "Why a decentralized Link-in-bio?":**


Screenshot 2023-06-22 at 8 12 37 PM

**New Image^ for "Openlinks.io and IPNS":**

**Comment by galaxyxtwo** [comment]
@noryev for reference here's how the Blog slider looked before these edits:



Screenshot 2023-06-21 at 6 48 36 PM

**Old image for "Follow us on Twitter":**

Screenshot 2023-06-22 at 6 49 16 PM

**Old image for "Why a decentralized Link-in-bio?":**

**Comment by galaxyxtwo** [comment]
Based on your suggestion @noryev the images in the blog slider now have info sections underneath with the title, date, and author. Screenshots of the most up to date edits are below. The titles are clickable and when clicked a new browser tab will open with the link.

Screenshot 2023-06-23 at 1 29 01 AM

Screenshot 2023-06-23 at 1 29 23 AM

**Comment by logan-wrld** [comment]
lgtm

**Pull request merged**
